[package]
name = "synth-backend"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
synth-core = { path = "../synth-core" }
synth-synthesis = { path = "../synth-synthesis" }
anyhow.workspace = true
thiserror.workspace = true
